#! /bin/sh

#xrandr --dpi 120
sxhkd &
redshift &
nm-applet &
xscreensaver &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12
bspc config click_to_focus 	true

nitrogen --restore &

compton &
$HOME/.config/polybar/launch.sh

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
