#! /bin/sh

#xrandr --dpi 120
sxhkd &
redshift &
dropbox start &
polybar example &

bspc monitor eDP-1 -d 1 2 3 4 5 6
bspc monitor DP-1 -d 7 8

bspc config border_width         2
bspc config window_gap          12
bspc config click_to_focus 	true
bspc config focus_follows_pointer true

nitrogen --restore &

#compton &
#$HOME/.config/polybar/launch.sh

bspc rule -a Emacs state=tiled
bspc rule -a teensy-gui state=tiled

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
